import type { Metadata } from 'next'
import Head from 'next/head'

import { Providers } from '@/providers/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="pt-BR">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/manifest.json"></link>
      </Head>
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  )
}

export default RootLayout
