import type { Metadata } from 'next'

import { Providers } from '@/providers/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="pt-BR">
      <Providers>
        <body>{children}</body>
      </Providers>
    </html>
  )
}

export default RootLayout
